name: Build
on: [push]
jobs:
  build:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: xcodebuild -project toyvm.xcodeproj -target toyvm -configuration Release
      - name: Archive
        run: |
          mkdir toyvm-bin
          cp -R build/Release/* toyvm-bin/
          zip -r9 toyvm-bin.zip toyvm-bin
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: toyvm-bin
          path: toyvm-bin.zip
